---
- hosts: all
 any_errors_fatal: true
 tasks:
    - name: Install git
     become: true
     ansible.builtin.package:
       name: git
       state: present

   - name: Checkout konstruktoid.hardening
     become: true
     ansible.builtin.git:
       repo: 'https://github.com/Tamiliplon/konstruktoid.hardening.git'
       dest: /etc/ansible/roles/konstruktoid.hardening
       version: master
