---
- name: Configure rkhunter
  become: true
  ansible.builtin.template:
    src: etc/default/rkhunter.j2
    dest: /etc/default/rkhunter
    backup: true
    mode: "0644"
    owner: root
    group: root
  when: ansible_os_family == "Debian"
  notify:
    - Run rkhunter propupd
  tags:
    - packages
    - rkhunter
    - M1049

...
